/**
* Changeset 004
* 1)- Correção problema de data + timezone do angular
* heroku pg:psql --app ipocket < /Users/eriklacerda/Documents/Personal/Projetos/ipocket/src/main/resources/config/postgres/db-postgres-004.sql
*/
/*ALTER TABLE BILL_ENTRY ALTER COLUMN DATE TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE ACCOUNT ALTER COLUMN CREATE_DATE TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE ACCOUNT_ENTRY ALTER COLUMN DATE TYPE TIMESTAMP WITH TIME ZONE;
*/

DROP TABLE IF EXISTS CATEGORY_GROUP;

CREATE TABLE CATEGORY_GROUP(
	ID 		SERIAL 	PRIMARY KEY,
	NAME 	VARCHAR(255) NOT NULL,
	USER_ID INTEGER NOT NULL REFERENCES user_account(id),
	
	CONSTRAINT CATEGORY_GROUP_CONST_01 UNIQUE (USER_ID,NAME)
);

ALTER TABLE CATEGORY 
	ADD COLUMN GROUP_ID INTEGER REFERENCES CATEGORY_GROUP(ID);
	
INSERT INTO CATEGORY_GROUP VALUES (DEFAULT, 'Alimentação', 10);
INSERT INTO CATEGORY_GROUP VALUES (DEFAULT, 'Ativos', 10);
INSERT INTO CATEGORY_GROUP VALUES (DEFAULT, 'Beleza', 10);
INSERT INTO CATEGORY_GROUP VALUES (DEFAULT, 'Cartão de Crédito', 10);
INSERT INTO CATEGORY_GROUP VALUES (DEFAULT, 'Casa', 10);
INSERT INTO CATEGORY_GROUP VALUES (DEFAULT, 'Educação', 10);
INSERT INTO CATEGORY_GROUP VALUES (DEFAULT, 'Empréstimo', 10);
INSERT INTO CATEGORY_GROUP VALUES (DEFAULT, 'Entradas', 10);
INSERT INTO CATEGORY_GROUP VALUES (DEFAULT, 'Entretenimento', 10);
INSERT INTO CATEGORY_GROUP VALUES (DEFAULT, 'Outros', 10);
INSERT INTO CATEGORY_GROUP VALUES (DEFAULT, 'Presentes', 10);
INSERT INTO CATEGORY_GROUP VALUES (DEFAULT, 'Roupas', 10);
INSERT INTO CATEGORY_GROUP VALUES (DEFAULT, 'Saúde', 10);
INSERT INTO CATEGORY_GROUP VALUES (DEFAULT, 'Taxas', 10);
INSERT INTO CATEGORY_GROUP VALUES (DEFAULT, 'Transferência', 10);
INSERT INTO CATEGORY_GROUP VALUES (DEFAULT, 'Transporte', 10);
INSERT INTO CATEGORY_GROUP VALUES (DEFAULT, 'Viagem', 10);

/*UPDATE CATEGORY_GROUP SET USER_ID = 10;*/

UPDATE CATEGORY SET GROUP_ID = 1 WHERE NAME = 'Alimentação';
UPDATE CATEGORY SET GROUP_ID = 2 WHERE NAME = 'Ativos';
UPDATE CATEGORY SET GROUP_ID = 3 WHERE NAME = 'Beleza';
UPDATE CATEGORY SET GROUP_ID = 4 WHERE NAME = 'Cartão de Crédito';
UPDATE CATEGORY SET GROUP_ID = 5 WHERE NAME = 'Casa';
UPDATE CATEGORY SET GROUP_ID = 6 WHERE NAME = 'Educação';
UPDATE CATEGORY SET GROUP_ID = 7 WHERE NAME = 'Empréstimo';
UPDATE CATEGORY SET GROUP_ID = 8 WHERE NAME = 'Entradas';
UPDATE CATEGORY SET GROUP_ID = 9 WHERE NAME = 'Entretenimento';
UPDATE CATEGORY SET GROUP_ID = 10 WHERE NAME = 'Outros';
UPDATE CATEGORY SET GROUP_ID = 11 WHERE NAME = 'Presentes';
UPDATE CATEGORY SET GROUP_ID = 12 WHERE NAME = 'Roupas';
UPDATE CATEGORY SET GROUP_ID = 13 WHERE NAME = 'Saúde';
UPDATE CATEGORY SET GROUP_ID = 14 WHERE NAME = 'Taxas';
UPDATE CATEGORY SET GROUP_ID = 15 WHERE NAME = 'Transferência';
UPDATE CATEGORY SET GROUP_ID = 16 WHERE NAME = 'Transporte';
UPDATE CATEGORY SET GROUP_ID = 17 WHERE NAME = 'Viagem';


ALTER TABLE CATEGORY DROP CONSTRAINT "u_const_01";
UPDATE CATEGORY SET NAME = SUBCATEGORY_NAME;
ALTER TABLE CATEGORY DROP COLUMN SUBCATEGORY_NAME;
ALTER TABLE CATEGORY ALTER COLUMN GROUP_ID SET NOT NULL;
ALTER TABLE CATEGORY ADD CONSTRAINT CATEGORY_CONST_01 UNIQUE (USER_ID,GROUP_ID,NAME);


/*
DROP TABLE IF EXISTS BUDGET;
CREATE TABLE BUDGET (
	ID				SERIAL 			PRIMARY KEY,
	DESCRIPTION		VARCHAR(255)	NOT NULL,
	TARGET			DECIMAL			NOT NULL,
	DATE			TIMESTAMP		NOT NULL
)

CREATE TABLE BUDGET_ENTRY(
	ID					SERIAL 			PRIMARY KEY,
	CATEGORY_ID			INTEGER	REFERENCES CATEGORY(ID),
	ESTIMATED_AMOUNT	DECIMAL	NOT NULL,
	CURRENT_AMOUNT		DECIMAL NOT NULL
)
*/