/**
* Changeset 002
* Acrescentando módulo de gestão de pagamentos programados (bills).
* heroku pg:psql --app ipocket < /Users/eriklacerda/Documents/Personal/Projetos/ipocket/src/main/resources/config/postgres/db-postgres-002.sql
*/

DROP TABLE IF EXISTS BILL_ENTRY;
DROP TABLE IF EXISTS BILL;


CREATE TABLE BILL (
	ID 				SERIAL PRIMARY KEY,
	DESCRIPTION		VARCHAR(255),
	CALC_TYPE		VARCHAR(1), /*F - Valor Fixo, A - Média ultimos lançamentos*/
	AVERAGE_COUNT	INTEGER,
	ACCOUNT_ID 		INTEGER REFERENCES ACCOUNT(ID), 
	CATEGORY_ID 	INTEGER REFERENCES CATEGORY(ID),
	USER_ID 		INTEGER REFERENCES user_account(id)
);

CREATE TABLE BILL_ENTRY (
	ID				SERIAL PRIMARY KEY,
	DATE			DATE,
	AMOUNT			DECIMAL,
	BILL_ID			INTEGER REFERENCES BILL(ID)
);

ALTER TABLE ACCOUNT DROP COLUMN IF EXISTS CREATE_DATE;
ALTER TABLE ACCOUNT ADD COLUMN CREATE_DATE DATE;
UPDATE ACCOUNT SET CREATE_DATE = '2015-01-01';
ALTER TABLE ACCOUNT ALTER COLUMN CREATE_DATE SET NOT NULL;